name: Interacting with LLMs

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  interacting_with_LLMs:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permission for script.sh
        run: chmod +x scripts/script.sh
        
      - name: Run script.sh
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.TOKEN }}
          API: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p upload_artifacts
          ./scripts/script.sh $TOKEN $REPOSITORY $ISSUE_NUMBER $API  > upload_artifacts/response.txt
        
      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: upload_artifacts
          
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: autocoder-artifact
          path: downloaded_artifacts

      - name: List files in artifacts
        run: ls -R downloaded_artifacts
    
