name: Opening a pull request

on:
  issues:
    types:
      - opened
      - reopened
      - labeled
permissions:
  contents: write
  pull-requests: write
  
jobs:
  opening_a_pull_request:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permission for script.sh
        run: chmod +x scripts/script.sh
        
      - name: Run script.sh
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.TOKEN }}
          API: ${{ secrets.OPENAI_API_KEY }}
        run: |
          mkdir -p upload_artifacts
          ./scripts/script.sh $TOKEN $REPOSITORY $ISSUE_NUMBER $API  > upload_artifacts/response.txt
        
      - name: Commit files
        run: |
          git config user.name "autocoder-bot"
          git config user.email "actions@github.com"

          git add -A
          git commit -m "Generate code for issue #${{ github.event.issue.number }}"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: autocoder-branch-${{ github.event.issue.number }}
          base: main
          labels: autocoder-bot



    
