name: Autocoder Generate Code

on:
  issues:
    types: [opened, reopened, labeled]

permissions:
  contents: write

jobs:
  generate:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: chmod +x ./scripts/script.sh

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: ./scripts/script.sh $GITHUB_TOKEN $REPOSITORY $ISSUE_NUMBER $OPENAI_API_KEY

      - name: Commit & push branch
        run: |
          git config user.email "actions@github.com"
          git config user.name "autocoder-bot"
          BRANCH=autocoder-branch-${{ github.event.issue.number }}
          git checkout -b $BRANCH
          git add .
          git commit -m "Add code snippets from issue #${{ github.event.issue.number }}" || echo "No changes"
          git fetch origin
          if git ls-remote --exit-code --heads origin $BRANCH; then
            echo "Remote branch exists, rebasing..."
            git checkout $BRANCH
            git pull --rebase origin $BRANCH
          else
            echo "Creating new branch..."
            git checkout -b $BRANCH
          fi
          git push origin $BRANCH
